db_vocab_size: 100
dim_feedforward: 1536
dropout: 0.1
embed_size: 384
epochs_per_episode: 5
final_p: 0.2
gamma_end: 0.0
gamma_start: 1.0
inference_batch_size: 128
initial_p: 0.5
learning_rate: 0.0001
max_train_batch_size: 128
n_episodes: 5
n_targets: 1600000
nhead: 12
num_decoder_layers: 6
num_encoder_layers: 6
rna_vocab_size: 5
sequence_length: 240
test_n_targets: 36000
test_size: 0.2
train_batch_size: 128
k_perm: 4
weight_decay: 0.0
update_train_structures: 1000
